language: java

deploy:
  provider: releases
  api-key: $GITHUB_API_KEY
  file: backend/target/Startreker-Netcracker-v1.jar
  skip_cleanup: true
  tag_name: $TRAVIS_TAG
  target_commitish: $TRAVIS_COMMIT
  on:
    branch: master
    tags: true

after_success:
  - bash <(curl -s https://codecov.io/bash)

script:
  - mvn install